name: prod Deployment

on:
  push:
    branches: [prod]
    paths:
      - "apps/app-admin/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: prod
    environment: prod

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Setup Lock File Path
        uses: actions/setup-node@v3

      - name: Prepare environment files
        run: |
          cp /root/.env ./apps/app-admin/.env

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: |
          pnpm install
        working-directory: apps/app-admin

      - name: Build Next app
        run: |
          pnpm run build
        working-directory: apps/app-admin

      - name: Check PM2 status before
        run: pm2 status

      - name: Restart Application with PM2
        run: |
          pm2 delete property || true  # Delete if exists, ignore error if not found
          pm2 start npm --name "property" -- start
        working-directory: apps/app-admin

      - name: Sync PM2
        run: pm2 save
